name: Deploy to GAE
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Deploy
        run: |
          echo ${KSS_PAY_SECRET} | base64 -d > ./pay/service_key.json
          echo ${KSS_MONITOR_SECRET} | base64 -d > ./monitor/service_key.json
          echo ${SERVICE_KEY} | base64 -d > ./service_key.json
          echo 'github-actions@${PROJ_NAME}.iam.gserviceaccount.com' | gcloud auth activate-service-account --key-file ./service_key.json
          gcloud app deploy app.yaml --project ${PROJ_NAME}
        env:
          CI: true
          PROJ_NAME: ${{ secrets.PROJ_NAME }}
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
          KSS_PAY_SECRET: ${{ secrets.KSS_PAY_SECRET }}
          KSS_MONITOR_SECRET: ${{ secrets.KSS_MONITOR_SECRET }}